name: checks
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  checks:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - run: yarn
      - run: yarn checks
      - run: yarn committed # ensure that checks did not modify files (eg formatting, linting, etc.)
